config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt.key: algun_codigo_secreto_aeiou
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
      #type: rabbit
    service:
      name: ${spring.application.name}
  #rabbitmq.host: microservicios-rabbitmq38
  sleuth:
    sampler:
      probability: 1
