eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt.key: algun_codigo_secreto_aeiou

spring:
  zipkin:
    base-url: http://zipkin-server:9411/
    sender:
      type: rabbit
    service:
      name: ${spring.application.name}
  rabbitmq.host: microservicios-rabbitmq38
  sleuth:
    sampler:
      probability: 1
