spring:   
  datasource:
      url: jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezone=UTC
      username: root
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate.dll-auto: create
logging:level:org:hibernate:SQL: debug 